export const SET_CATEGORY_LIST = 'SET_CATEGORY_LIST';
export const SET_SUGGESTION_LIST = 'SET_SUGGESTION_LIST';
export const SET_SELECTED_MOVIE = 'SET_SELECTED_MOVIE';
export const REMOVE_SELECTED_MOVIE = 'REMOVE_SELECTED_MOVIE';
